/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonFooter: (typeof import('./components/commonFooter/CommonFooter.vue'))['default'];
    DialoguePanel: (typeof import('./components/dialoguePanel/DialoguePanel.vue'))['default'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
    ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup'];
    ElDialog: (typeof import('element-plus/es'))['ElDialog'];
    ElForm: (typeof import('element-plus/es'))['ElForm'];
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElPopover: (typeof import('element-plus/es'))['ElPopover'];
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton'];
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
    EulerDialog: (typeof import('./components/EulerDialog.vue'))['default'];
    PrivacyText: (typeof import('./components/commonFooter/PrivacyText.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SessionCard: (typeof import('./components/sessionCard/SessionCard.vue'))['default'];
    SvgIcon: (typeof import('./components/SvgIcon.vue'))['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import('element-plus/es'))['ElLoadingDirective'];
  }
}
